replicaCount: 1

image:
  repository: eclipse-mosquitto
  tag: 2.0-openssl
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 1883

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
