apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mosquitto-config
  labels:
    app: {{ .Chart.Name }}
data:
  default.conf: |
    persistence true
    persistence_location /mosquitto/data/
    log_dest stdout
