apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mosquitto
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      initContainers:
        - name: copy-default-config
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - >
              if [ ! -f /mosquitto/config/mosquitto.conf ]; then
                cp /mosquitto/config-default/mosquitto.conf /mosquitto/config/mosquitto.conf;
              fi;
          volumeMounts:
            - name: mosquitto-default
              mountPath: /mosquitto/config-default
            - name: mosquitto-config
              mountPath: /mosquitto/config
      containers:
        - name: mosquitto
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 1883
          volumeMounts:
            - name: mosquitto-data
              mountPath: /mosquitto/data
            - name: mosquitto-default
              mountPath: /mosquitto/config-default
            - name: mosquitto-config
              mountPath: /mosquitto/config
      volumes:
        - name: mosquitto-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-mosquitto-data
        - name: mosquitto-default
          configMap:
            name: {{ .Release.Name }}-mosquitto-config
        - name: mosquitto-config
          emptyDir: {}
